feat: connections and pools
terraform-google-modules/terraform-google-composer pull request #25
Opened 2021-10-21 14:37 UTC by jond3k

New optional features:

- Manage connections using the underlying `airflow connections` command
- Manage pools using the underlying `airflow pools` command
- Enable underlying GKE clusters authorized networks -- needed to run arbitrary commands via public IP
- Includes examples and integration tests

Note that teardowns for the new tests are currently disabled due to a race between cluster shutdown and running the gcloud destroy commands. One potential fix is to add the following `after` hooks, but I can't see a way to do this:

```
# after hook for connections
terraform state rm 'module.simple-composer.module.example-3.module.gcloud.null_resource.run_destroy_command[0]'
terraform state rm 'module.simple-composer.module.simple-composer-environment.module.airflow-connections["example-1"].module.gcloud.null_resource.run_destroy_command[0]'
terraform state rm 'module.simple-composer.module.simple-composer-environment.module.airflow-connections["example-2"].module.gcloud.null_resource.run_destroy_command[0]'
terraform state rm 'module.simple-composer.module.simple-composer-environment.module.master-authorized-networks.module.gcloud.null_resource.run_command[0]'
terraform state rm 'module.simple-composer.module.simple-composer-environment.module.master-authorized-networks.module.gcloud.null_resource.run_destroy_command[0]'

# after hook for pools
terraform state rm 'module.simple-composer.module.standalone-pool-1.module.gcloud.null_resource.run_destroy_command[0]'
terraform state rm 'module.simple-composer.module.simple-composer-environment.module.airflow-pools["inline-1"].module.gcloud.null_resource.run_destroy_command[0]'
terraform state rm 'module.simple-composer.module.simple-composer-environment.module.master-authorized-networks.module.gcloud.null_resource.run_destroy_command[0]
```

2021-10-21 16:25 UTC, morgante commented
> Note that teardowns for the new tests are currently disabled due to a race between cluster shutdown and running the gcloud destroy commands.

Please file an issue so we can track a longer-term workaround, ideally using our new test framework.

2021-10-21 17:42 UTC, morgante commented
> OK. Out of interest what is your new test framework? Are there any examples using it already?

Sure! It's [here](https://pkg.go.dev/github.com/GoogleCloudPlatform/cloud-foundation-toolkit/infra/blueprint-test). Here's [an example](https://github.com/terraform-google-modules/terraform-google-network/tree/master/test/integration). We'd definitely love your feedback if you get a chance!

2021-11-15 16:19 UTC, jond3k commented
@morgante is there anything left before we can merge this? I would like to start using the official module rather than my own fork and I have other PRs I'd like to raise.

2021-11-15 20:47 UTC, morgante requested changes
> @morgante top level changes are now removed

I still see top-level changes in the main module. Maybe a push was missed?

2021-11-15 20:47 UTC, morgante commented on test/fixtures/airflow-connection/variables.tf
> +variable "composer_sa" {
Please don't make these variables. Just create them in the fixture or example.

I know this is different from how the existing example works, but the example you're working from is quite old and our standards have changed.

2021-11-16 10:37 UTC, jond3k commented on test/fixtures/airflow-connection/variables.tf
> +variable "composer_sa" {
Can you please link me to the new standard @morgante

2021-11-18 03:37 UTC, bharathkkb commented on test/fixtures/airflow-connection/variables.tf
> +variable "composer_sa" {
@jond3k https://github.com/terraform-google-modules/terraform-google-network/tree/master/examples/simple_project is a good example. In most cases `project_id` should be the only input for required for a fixture. Do you create `composer_sa` in setup because it throws a value cannot be determined until apply error?

2021-11-19 14:03 UTC, jond3k commented on test/fixtures/airflow-connection/variables.tf
> +variable "composer_sa" {
That's how the existing fixture does it. I've pushed a change which removes the variable however 'guessing' a value like a service account email instead of using the outputs of the resource that generates it not a good idea as it'll break if (1) the service account name in the setup harness changes (2) the way google names service accounts changes (3) the test framework at any point combines the setup and fixture into one step

2021-11-19 14:36 UTC, jond3k commented on test/fixtures/airflow-connection/variables.tf
> +variable "composer_sa" {
I ran the integration tests myself and they succeeded. They've failed here but I can't see the logs

2021-11-24 17:55 UTC, bharathkkb commented on build/int.cloudbuild.yaml
> +- id: create airflow-connection-local
build seems to be flaky due to parallel steps populating the provider cache. Can you move all create-* to a single step like 
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/cff1c1be2658fc88ea793dca73a5156b849050c3/build/int.cloudbuild.yaml#L27-L31

2021-11-24 20:39 UTC, bharathkkb requested changes

2021-11-24 20:39 UTC, bharathkkb commented on main.tf
> +  web_server_allowed_ip_ranges     = var.web_server_allowed_ip_ranges
We seem to be plumbing everything to the `create_environment` submodule. Can we keep this simple with minimal inputs while showcasing how to use `create_environment` directly for more configuration options?

2021-11-24 20:39 UTC, bharathkkb commented on modules/airflow_connection/main.tf
> +  version                = "~> 3"
pin to a minor version `3.x`

2021-11-24 20:39 UTC, bharathkkb commented on modules/airflow_connection/variables.tf
> +variable "enabled" {
Whats the usecase for exposing this? Its seems like if they invoke this module, they would want the resources to be created?

2021-11-24 20:39 UTC, bharathkkb commented on modules/airflow_connection/variables.tf
> +
nit: extra lines

2021-11-24 20:39 UTC, bharathkkb commented on modules/airflow_connection/variables.tf
> +
```suggestion
```

2021-11-24 20:39 UTC, bharathkkb commented on modules/airflow_connection/main.tf
> +  create_cmd_entrypoint  = "gcloud"
this is a module default, so we can skip this and destroy_cmd_entrypoint

2021-11-24 20:39 UTC, bharathkkb commented on modules/airflow_pool/main.tf
> +  version                = "3.0.1"
same comments as `airflow_connection`

2021-11-24 20:39 UTC, bharathkkb commented on modules/airflow_pool/variables.tf
> +  default     = ""
Maybe a default like `Pool managed by Terraform` makes sense?

2022-01-06 12:49 UTC, nlamirault commented on modules/airflow_pool/variables.tf
> +  default     = ""
`Managed by Terraform` like in other Google modules ?

2022-01-06 17:28 UTC, morgante commented on modules/airflow_pool/variables.tf
> +  default     = ""
Yep.

2022-01-16 21:08 UTC, jond3k commented
I don't believe there's anything else outstanding on this, @bharathkkb @morgante ?

2022-01-19 21:17 UTC, morgante approved these changes
Thanks for following through on this and your patience with the review process.

2022-01-19 21:17 UTC, merged