feature: cloud composer v2
terraform-google-modules/terraform-google-composer pull request #36
Opened 2022-02-01 18:47 UTC by diegolnasc

Including new autoscale version (V2) of Airflow in a separate module. So the old version remains intact and we can use the new version separately.

The decision to separate was based on the contract change (terraform) to create the two environments.

2022-02-01 21:03 UTC, diegolnasc commented
@bharathkkb Hey,
Can you give me a hint of what is happening in the integration test?

Locally my tests are all passing. Therefore, I believe there is some policy that prevents putting the mandatory role (roles/composer.ServiceAgentV2Ext) for Workload Identity in composer sa.

2022-02-02 06:28 UTC, bharathkkb commented
Hi @diegolnasc 
The error seems to be due to kitchen-tf not being able to find the test
```
-----> Starting Test Kitchen (v2.7.2)
>>>>>> 
No instances for regex `simple-composer-env-local', try running `kitchen list'
```
In the diff I saw some renames for the test, you will also need to update 
https://github.com/terraform-google-modules/terraform-google-composer/blob/8b03071a22ddb465d06a9a362ec62c32c03f1743/kitchen.yml#L23-L34
and https://github.com/terraform-google-modules/terraform-google-composer/blob/master/build/int.cloudbuild.yaml accordingly.

2022-02-02 06:33 UTC, bharathkkb requested changes
Thanks for the PR @diegolnasc 
Could you elaborate a bit on the differences between both versions and why users would need both? We can also open an issue if thats easier for discussion.

Usually having two versions introduces additional complexity as users are not certain which is recommended and maintenance also increases.

2022-02-02 11:43 UTC, diegolnasc commented
> Thanks for the PR @diegolnasc Could you elaborate a bit on the differences between both versions and why users would need both? We can also open an issue if thats easier for discussion.
> 
> Usually having two versions introduces additional complexity as users are not certain which is recommended and maintenance also increases.

Well, the main difference between the two versions is the infrastructure.

V1 has Airflow core services (scheduler, workers) with a fixed instance number. These services run on the default node pool of a managed instance of GKE (standard). So the best way to run jobs is to create other node pools, avoiding competing with airflow resources. Anyway, there is the trivial scaling problem, airflow workers are fixed.

V2 "fixes" these issues by allowing airflow worker scaling and also has more flexibility in sizing standard airflow core services. Additionally, Airflow runs on GKE Autopilot, also solving the need to create separate node pools for jobs.

[List of major differences.](https://cloud.google.com/composer/docs/concepts/versioning/composer-versioning-overview)

---

The Composer page is also a bit confusing. It doesn't make it clear which version is recommended and has a separate flow for each version.

Anyway, Cloud Composer 1 versions are released until the end of **March 2023**. Therefore, I think it is correct to assume that the recommended version is V2.

2022-02-02 14:35 UTC, diegolnasc commented
> Hi @diegolnasc The error seems to be due to kitchen-tf not being able to find the test
> 
> ```
> -----> Starting Test Kitchen (v2.7.2)
> >>>>>> 
> No instances for regex `simple-composer-env-local', try running `kitchen list'
> ```
> 
> In the diff I saw some renames for the test, you will also need to update
> 
> https://github.com/terraform-google-modules/terraform-google-composer/blob/8b03071a22ddb465d06a9a362ec62c32c03f1743/kitchen.yml#L23-L34
> 
> 
> and https://github.com/terraform-google-modules/terraform-google-composer/blob/master/build/int.cloudbuild.yaml accordingly.

Ops, my bad!

2022-02-03 23:38 UTC, bharathkkb requested changes
Thanks for the clarification @diegolnasc 
Looking at the [docs](https://cloud.google.com/composer/docs/concepts/versioning/composer-versioning-overview) and provider info([composer1](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#argument-reference---cloud-composer-1), [composer2](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#argument-reference---cloud-composer-2)) it looks like we are supporting both versions concurrently so it makes sense for a separate module. Combining it maybe more complicated and confusing for end users.

/cc @morgante @kunalkg11 any thoughts on this?

2022-02-03 23:38 UTC, bharathkkb commented on examples/airflow_connection/variables.tf
> +}
Lets hardcode examples as much as possible

2022-02-03 23:38 UTC, bharathkkb commented on modules/create_environment_v2/README.md
> +# Module Cloud Composer Environment (V2)
Can we add some more links to cloud docs on what is Composer Env v2

2022-02-03 23:38 UTC, bharathkkb commented on modules/create_environment_v2/versions.tf
> +  provider_meta "google" {
Lets add google-beta too since I saw some resources using the beta provider

2022-02-03 23:38 UTC, bharathkkb commented on examples/simple_composer_env_v1/variables.tf
> + * Copyright 2020 Google LLC
Here and throughout
```suggestion
 * Copyright 2022 Google LLC
```

2022-02-03 23:38 UTC, bharathkkb commented on modules/create_environment_v2/main.tf
> +        }] : []
Do we need `.enabled`? Cant we do something like for some of these blocks like scheduler, web_server, worker etc?

```suggestion
        for_each = var.scheduler != null ? [var.scheduler] : []
```

2022-02-04 00:28 UTC, diegolnasc commented on modules/create_environment_v2/README.md
> +# Module Cloud Composer Environment (V2)
I also add some links in the main READM.md.

https://github.com/terraform-google-modules/terraform-google-composer/blob/ee31caeaf63cd8daf27b41094b2bac3a02337359/README.md?plain=1#L10-L15

2022-03-03 13:33 UTC, diegolnasc commented
@bharathkkb Is there still interest in the update or can I close the PR?

2022-03-28 21:41 UTC, mwallace582 commented
Is there still work that needs to be done here? It looks to me like all the review comments have been addressed, and nothing else is blocking the merge.

I would be happy to lend a hand if any further changes are needed.

2022-03-29 04:25 UTC, bharathkkb approved these changes

2022-03-29 04:25 UTC, bharathkkb commented
@diegolnasc apologies for the delay

2022-03-29 04:26 UTC, merged